services:
  web:
    build:
      context: .
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://mock:8080
      - VITE_IMAGE_HOST=https://dummyimage.com
    depends_on:
      - mock

  mock:
    image: wiremock/wiremock:2.35.0
    ports:
      - "3001:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
