services:
  mock:
    image: wiremock/wiremock:2.35.0
    ports:
      - "8080:8080"
    volumes:
      - ./wiremock:/home/wiremock
    command: [ "--verbose" ]

  web:
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:8080}
        VITE_IMAGE_HOST: ${VITE_IMAGE_HOST:-https://dummyimage.com}
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8080}
      - VITE_IMAGE_HOST=${VITE_IMAGE_HOST:-https://dummyimage.com}
    ports:
      - "5173:80"
    depends_on:
      - mock
